"""auto-vote

Revision ID: 9a1f7a702886
Revises: d53b75e514e8
Create Date: 2022-12-06 12:43:13.701163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1f7a702886'
down_revision = 'd53b75e514e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
