"""auto-vote

Revision ID: d53b75e514e8
Revises: b83fed5be678
Create Date: 2022-12-06 12:40:58.373132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53b75e514e8'
down_revision = 'b83fed5be678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
